INSERT INTO books (id, title, author, isbn, price, description, cover_image, is_deleted)
VALUES (1, 'The Secret of the Forest', 'Virginia Wolfe', '1234567890', 47.55,
        'A thrilling story of adventure and mystery in the forest.',
        'https://example.com/coverimage1.jpg', false),
       (2, 'Journey to the Unknown', 'Michael Stevens', '2345678901', 59.99,
        'An exciting journey to uncover unknown secrets.', 'https://example.com/coverimage2.jpg',
        false),
       (3, 'Mysteries of the Deep', 'Harriet Potter', '3456789012', 39.90,
        'A deep dive into the unknown depths of the ocean.', 'https://example.com/coverimage3.jpg',
        false),
       (4, 'Adventures in Flatland', 'D. E. Abbott', '4567890123', 22.75,
        'Adventures in a two-dimensional world.', 'https://example.com/coverimage4.jpg', false),
       (5, 'Galactic Tales', 'K. L. Smith', '6789012345', 30.50,
        'Tales of adventure across the galaxy.', 'https://example.com/coverimage6.jpg', false),
       (6, 'Whispering Shadows', 'Robert Jordan', '7890123456', 45.20,
        'A mystery shrouded in shadows.', 'https://example.com/coverimage7.jpg', false),
       (7, 'Magic and Mayhem', 'J. K. Rowling', '8901234567', 38.99,
        'A tale of magic and adventure.', 'https://example.com/coverimage8.jpg', false),
       (8, 'The Quantum Enigma', 'Brian Greene', '9012345678', 55.45,
        'Unraveling the mysteries of quantum physics.', 'https://example.com/coverimage9.jpg',
        false),
       (9, 'Dreams of Tomorrow', 'Isaac Asimov', '9123456789', 36.85,
        'A visionary look into the future.', 'https://example.com/coverimage10.jpg', false),
       (10, 'Dreams of Tomorrow', 'Isaac Asimov', '9123456789а', 1212.00,
        'A visionary look into the future.', 'https://example.com/coverimage10.jpg', false),
       (11, 'The Last Whisper', 'Unknown Author', '184777106X', 0.00,
        'An unpublished script found in an ancient library, shrouded in mystery.',
        'https://example.com/coverimage11.jpg', false);
