services:
  db:
    image: mysql:latest
    container_name: mysql_book_store
    restart: unless-stopped
    env_file:
      - ./.env
    ports:
      - $MYSQL_LOCAL_PORT:$MYSQL_DOCKER_PORT
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_USER=$MYSQLDB_USER
      - MYSQL_PASSWORD=$MYSQLDB_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h localhost -u root -p$MYSQLDB_ROOT_PASSWORD || exit 1" ]
      interval: 30s
      timeout: 30s
      retries: 3
    networks:
      - app_network

  app:
    image: book_store
    container_name: book_store
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure
    build: .
    env_file: ./.env
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
      - $DEBUG_PORT:$DEBUG_PORT
    environment:
      SPRING_APPLICATION_JSON: >-
        {
          "spring.datasource.url": "jdbc:mysql://${MYSQL_HOST}:${MYSQL_DOCKER_PORT}/${MYSQLDB_DATABASE}",
          "spring.datasource.username": "${MYSQLDB_USER}",
          "spring.datasource.password": "${MYSQLDB_PASSWORD}",
          "spring.jpa.show-sql" : "true",
          "spring.datasource.driver-class-name": "com.mysql.cj.jdbc.Driver"
        }
      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
