INSERT INTO categories (id, name, description, is_deleted)
VALUES  (1, 'Fantasy Adventure', 'Fantasy Adventure', false),
        (2, 'Science Fiction', 'Science Fiction', false),
        (3, 'Mystery Thriller', 'Mystery Thriller', false),
        (4, 'Historical Fiction', 'Historical Fiction', false),
        (5, 'Romance', 'Romance', false),
        (6, 'Horror', 'Horror', false),
        (7, 'Dystopian', 'Dystopian', false),
        (8, 'Young Adult', 'Young Adult', false),
        (9, 'Crime Drama', 'Crime Drama', false),
        (10, 'Action and Adventure', 'Action and Adventure', false),
        (11, 'Paranormal Romance', 'Paranormal Romance', false),
        (12, 'Steampunk', 'Steampunk', false),
        (13, 'Magical Realism', 'Magical Realism', false),
        (14, 'Epic Fantasy', 'Epic Fantasy', false),
        (15, 'Space Opera', 'Space Opera', false),
        (16, 'Contemporary Fiction', 'Contemporary Fiction', false),
        (17, 'Gothic Fiction', 'Gothic Fiction', false),
        (18, 'Cyberpunk', 'Cyberpunk', false),
        (19, 'Detective Mystery', 'Detective Mystery', false),
        (20, 'Psychological Thriller', 'Psychological Thriller', false);